# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Approximate pi
#'
#' Return an estimate of pi.
#' @param N is sample size for approximation
#' @export
approx_pi <- function(N) {
    .Call(`_pkgrcpp_approx_pi`, N)
}

#' Approximate pi
#'
#' Return an estimate of pi.
#' @param N is sample size for approximation
#' @export
approx2_pi <- function(N) {
    .Call(`_pkgrcpp_approx2_pi`, N)
}

#' Add Two Numbers
#'
#' Return the sum of two numbers.
#' @param x is the first numeric value
#' @param y is the second numeric value
#' @export
add_cpp <- function(x, y) {
    .Call(`_pkgrcpp_add_cpp`, x, y)
}

#' Add a vector of Numbers
#'
#' Return the sum of a vector.
#' @param x is a numeric vector
#' @export
sumC <- function(x) {
    .Call(`_pkgrcpp_sumC`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_pkgrcpp_RcppExport_registerCCallable`)
})
